# Generated by Django 6.0.3 on 2026-04-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='caption',
            field=models.CharField(default='No caption', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='title',
            field=models.CharField(default='Untitled meme', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situation',
            name='text',
            field=models.CharField(),
        ),
    ]
