# Generated by Django 6.0.3 on 2026-04-21 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meme_caption_meme_title_alter_situation_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='image',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='player',
        ),
        migrations.AddField(
            model_name='meme',
            name='author',
            field=models.ForeignKey(default='No caption', on_delete=django.db.models.deletion.CASCADE, related_name='memes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='image_url',
            field=models.URLField(default='https://example.com/default.jpg'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='caption',
            field=models.CharField(default='No caption', max_length=255),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(default='Untitled meme', max_length=100),
        ),
    ]
