# Generated by Django 6.0.3 on 2026-04-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_memecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecard',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
